"""Phase 5: run the league analysis and write research/LEAGUE_FINDINGS.md.

    python -m research.run_league                 # league data if fetched, else dev sample
    python -m research.run_league --source dev    # force the 7-series dev sample
    python -m research.run_league --simulations 4000 --draws 2000

The markdown is generated from the numbers, so it always matches the code.
"""

import argparse
import json

from research.data import RESULTS, ROOT
from research.league import (
    BLOWOUT_MARGIN, PRIMARY_MIN_MINUTES, PRIMARY_TOP_USAGE, Q,
    build_transitions, findings, load_dataset,
)

DOC = ROOT / "research" / "LEAGUE_FINDINGS.md"


def pct(value):
    return "n/a" if value is None else f"{100 * value:.0f}%"


def interval(block, scale=100, unit="%", digits=0):
    if not block or block.get("estimate") is None:
        return "n/a"
    est = block["estimate"] * scale
    if block.get("low") is None:
        return f"{est:.{digits}f}{unit}"
    return (f"{est:.{digits}f}{unit} (95% CI {block['low'] * scale:.{digits}f}"
            f"{unit} to {block['high'] * scale:.{digits}f}{unit})")


def render(source, f, seasons):
    a, nb = f["all"], f["no_blowouts"]
    small = f["series"] < 20
    lines = [
        "# League findings",
        "",
        f"Generated by `python -m research.run_league` from the **{source}** dataset: "
        f"{f['series']} series, {f['transitions']} consecutive-game transitions, "
        f"{f['primary_players']} primary offensive players ({f['primary_transitions']} transitions).",
        f"Seasons: {', '.join(seasons)}.",
        "",
    ]
    if small:
        lines += [
            "> **Development sample.** With fewer than 20 series, intervals are wide and",
            "> these numbers show the pipeline working, not league conclusions. Run",
            "> `python -m scripts.fetch_playoffs` locally, then rerun this script.",
            "",
        ]
    lines += [
        "All significance is model-based (see `FINDINGS.md`): a *robust* adjustment has",
        f"league q < {Q:.2f} on both the time and possession noise bases. Intervals",
        "resample whole series (cluster bootstrap). Nothing here identifies coaching",
        "intent; see `FACE_VALIDITY.md`.",
        "",
        "## 1. How often do matchup changes survive the noise baseline?",
        "",
        f"- Primary offensive players: {interval(a.get('robust_rate_primary'))} of transitions are robust.",
        f"- Non-primary players: {pct(f['robust_rate_non_primary'])}.",
        f"- Of {a.get('large_raw_changes', 0)} large raw changes (TVD ≥ 0.30) for primary players, "
        f"{pct(a.get('large_raw_surviving_noise'))} survive.",
        f"- Excluding blowouts: {interval(nb.get('robust_rate_primary'))} "
        f"(n = {nb['n']}).",
        "",
        "## 2. Overlap or assignment?",
        "",
        "Share of summed TVD in robust, well-covered transitions of primary players:",
        "",
        "| Component | All games | Excluding blowouts |",
        "| --- | --- | --- |",
    ]
    for component, label in (("overlap", "Overlap / rotation"),
                             ("assignment", "Assignment"),
                             ("entry_exit", "Entry / exit")):
        lines.append(f"| {label} | {interval(a.get(f'share_{component}'))} | "
                     f"{interval(nb.get(f'share_{component}'))} |")
    lines += [
        "",
        "## 3. Do adjustments follow losses?",
        "",
        f"- Robust-adjustment rate when the defending team lost the earlier game: "
        f"{pct(a.get('robust_rate_after_def_loss'))}; after a win: {pct(a.get('robust_rate_after_def_win'))}.",
        f"- Difference (loss − win): {interval(a.get('loss_minus_win'), unit=' pp')}.",
        f"- Excluding blowouts: {interval(nb.get('loss_minus_win'), unit=' pp')}.",
        "",
        "## 4. What happens to the offensive player next game?",
        "",
        "Regression of the later game's deviation from the player's own series",
        "average on a robust-adjustment indicator, controlling for the earlier",
        "game's deviation (regression to the mean). Association only.",
        "",
        f"- Points per 36: {interval(a.get('robust_coef_pts36_dev'), scale=1, unit='', digits=1)}"
        f"; excluding blowouts {interval(nb.get('robust_coef_pts36_dev'), scale=1, unit='', digits=1)}.",
        f"- True shooting: {interval(a.get('robust_coef_ts_dev'), unit=' pp', digits=1)}"
        f"; excluding blowouts {interval(nb.get('robust_coef_ts_dev'), unit=' pp', digits=1)}.",
        "",
        "## Definitions",
        "",
        f"- Primary offensive player: ≥ {PRIMARY_MIN_MINUTES} minutes per game played and team top-{PRIMARY_TOP_USAGE}"
        " in usage per game (FGA + 0.44 FTA + turnovers), from box scores.",
        f"- Blowout: final margin ≥ {BLOWOUT_MARGIN} in either game of the transition"
        f" ({pct(f['blowout_share_primary'])} of primary transitions).",
        f"- Low decomposition coverage (< 0.80): {pct(f['low_coverage_share_primary'])} of primary transitions;"
        " excluded from the component shares.",
        "- Transitions across games a player missed are excluded.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", choices=["auto", "league", "dev"], default="auto")
    parser.add_argument("--simulations", type=int, default=4000)
    parser.add_argument("--draws", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=20261005)
    args = parser.parse_args()

    source, bundles = load_dataset(args.source)
    table = build_transitions(bundles, args.simulations, args.seed)
    result = findings(table, args.draws)
    seasons = sorted({m.season.iloc[0] for _, m, _, _ in bundles})
    out = RESULTS / "league"
    out.mkdir(parents=True, exist_ok=True)
    table.to_csv(out / f"transitions_{source}.csv", index=False)
    (out / f"findings_{source}.json").write_text(
        json.dumps({"source": source, "seasons": seasons, **result}, indent=2, default=float) + "\n")
    DOC.write_text(render(source, result, seasons))
    print(f"{source}: {result['series']} series, {result['transitions']} transitions; wrote {DOC.name}")


if __name__ == "__main__":
    main()
